import { Class, Style, Type } from "../Enums";
import { Unit } from "../Unit";
import { BuffCrew, DBFEnemy, HealCrew } from "./Tags";

export let characters: Unit[] = [
    {
        id: 1445,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Boa Hancock',
        name2: 'Snake Princess',
        altnames: ['6+', 'Boa', 'Legend', 'QCK', 'V1'],
        class: Class.SHT,
        classIcon: '',
        class2: Class.FSP,
        class2Icon: '',
        type: Type.QCK,
        style: Style.HLR,
        styleIcon: '',
        rumbleSpecial: 'Level 10 (34 CT): Targets 1 enemy for 1000 fixed damage, targets enemies wide range for tier 4 SPD down (20 s.), heals HP of all crew members by 1.25x own RCV',
        rumbleSkill: 'Level 5: When own HP is above 50% targets all QCK/PSY allies for tier 9 ATK boost. When own HP is below 50% targets all QCK/PSY allies for tier 9 RCV boost ',
        rumblePattern: 'Normal, tier 2 Heal surrounding allies (mid-range), Normal, tier 2 Heal surrounding allies (short range)',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Bind (50% chance)',
        tags: [BuffCrew.ATK, BuffCrew.RCV, DBFEnemy.DMG_FIXED, DBFEnemy.SPD, HealCrew.HEAL]
    },
    {
        id: 1879,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Bartolomeo the Cannibal',
        name2: 'Captain of the Barto Club Pirates',
        altnames: ['Raid', 'Barto'],
        class: Class.STK,
        classIcon: '',
        class2: Class.DRV,
        class2Icon: '',
        type: Type.PSY,
        style: Style.DEF,
        styleIcon: '',
        rumbleSpecial:  'Level 10 (25 CT): Targets 1 enemy for 2350 fixed damage. Targets self for tier 15 ATK boost (24 s.)',
        rumbleSkill: 'First 25 seconds after battle start: targets crew for tier 5 HP boost and tier 1 DEF boost',
        rumblePattern: 'Normal, Normal, Strong',
        rumbleTarget: 'Enemy with less HP left',
        rumbleResistances: '',
        tags: [DBFEnemy.DMG_FIXED, BuffCrew.ATK, BuffCrew.HP, BuffCrew.DEF]
    },
    {
        id: 1985,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Luffy&Ace',
        name2: '',
        altnames: ['Lace', 'Rufy', 'Luffy', 'Ace', 'dual', 'legend'],
        class: Class.DUAL,
        classIcon: '',
        class2: Class.NONE,
        class2Icon: '',
        type: Type.DUAL,
        style: Style.SUP,
        styleIcon: '',
        rumbleSpecial:  'Level 10 (27 CT): Targets Free Spirit allies for tier 3 ATK and DEF boost ( 20 s.). Targets wide-range enemies on the side for damage by 0.65x own ATK',
        rumbleSkill: 'Level 5: Targets Free Spirit allies for tier 5 ATK boost and level 2 Crit chance boost',
        rumblePattern: 'Strong, Strong, Lv 1 Heal on nearby allies (short range), Strong',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Paralysis (50% chance)',
        tags: [BuffCrew.ATK, BuffCrew.DEF, DBFEnemy.DMG, BuffCrew.CRIT]
    },
    {
        id: 2034,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Borsalino',
        name2: 'Navy HQ Greatest Military Power',
        altnames: ['Kizaru', '6+', 'Legend', 'PSY'],
        class: Class.SLA,
        classIcon: '',
        class2: Class.SHT,
        class2Icon: '',
        type: Type.PSY,
        style: Style.SUP,
        styleIcon: '',
        rumbleSpecial: 'Level 10 (15 CT): Targets 4 enemies for damage by 1x own ATK, targets Slasher/Shooter allies for tier 7 ATK boost (24 s.)',
        rumbleSkill: 'Level 5: Targets Slasher/Shooter allies for tier 6 SPD boost, during first 30 seconds of battle targets Slasher/Shooter allies for tier 4 CT loading speed boost',
        rumblePattern: 'Normal, Strong, tier 1 Heal surrounding allies (mid-range), Normal',
        rumbleTarget: 'Enemy with highest ATK',
        rumbleResistances: 'Silence (70% chance)',
        tags: [DBFEnemy.DMG, BuffCrew.ATK, BuffCrew.SPD, BuffCrew.CTS,]
    },
    {
        id: 2181,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Whitebeard&Marco',
        name2: 'The Fierce Battle at the Paramount War',
        altnames: ['Warco', 'Dual', 'WB&Marco', 'Legend'],
        class: Class.DUAL,
        classIcon: '',
        class2: Class.NONE,
        class2Icon: '',
        type: Type.DUAL,
        style: Style.DEF,
        styleIcon: '',
        rumbleSpecial:  'Level 10 (27 CT): Targets all enemies for 32% HP Cut, Heals own HP by 2.15x own RCV',
        rumbleSkill: 'Level 5: Targets crew for tier 5 Guard rate buff, when own HP is below 50% targets self for tier 3 DEF boost',
        rumblePattern: 'Normal, Normal, tier 2 Heal self',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Silence (50% chance)',
        tags: [DBFEnemy.CUT, BuffCrew.HEAL, BuffCrew.GRD, BuffCrew.DEF]
    },
    {
        id: 2444,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Donquijote Doflamingo',
        name2: `God's Sanction`,
        altnames: ['V1', '6+', 'Doffy', 'Doflamingo', 'INT'],
        class: Class.DRV,
        classIcon: '',
        class2: Class.CER,
        class2Icon: '',
        type: Type.INT,
        style: Style.DEF,
        styleIcon: '',
        rumbleSpecial: 'Level 10 (27 CT): Targets 3 enemies for damage by 2x own ATK,. Targets Driven/Slasher allies for tier 5 DEF boost and tier 6 CRIT chance boost (19 s.)',
        rumbleSkill: 'Level 5: Targets Driven/Slasher allies for tier 6 HP boost; first 30 seconds from start of the battle targets Slasher/Driven allies for tier 3 DEF boost and tier 6 ATK boost',
        rumblePattern: 'Normal, Normal, tier 2 Heal self',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Seldom heals own HP by 150 when under 50%',
        tags: [DBFEnemy.DMG, BuffCrew.DEF, BuffCrew.CRIT, BuffCrew.HP, BuffCrew.ATK]
    },
    {
        id: 2588,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Nami',
        name2: 'Cat Burglar deceiving the world',
        altnames: ['Legend', 'Nami', '6+', 'Whole Cake Island', 'DEX'],
        class: Class.CER,
        classIcon: '',
        class2: Class.STK,
        class2Icon: '',
        type: Type.DEX,
        style: Style.OBS,
        styleIcon: '',
        rumbleSpecial: 'Level 10 (22 CT): Targets enemies (wide range) for damage by 1.1x own ATK and for Paralysis (30% chance, 24 s.)',
        rumbleSkill: 'Level 5: Targets DEX allies for tier 6 CT loading speed boost. When 50 or less seconds are left, targets DEX allies for tier 2 CT loading speed boost',
        rumblePattern: 'Normal, tier 2 Heal self, Strong, tier 1 Heal surrounding allies (mid-range)',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Seldom heals own HP by 150',
        tags: [DBFEnemy.DMG, DBFEnemy.PAR, BuffCrew.CTS]
    },
    {
        id: 2958,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Monkey D. Luffy',
        name2: 'The Great Snake Surpassing The Future',
        altnames: ['V2', 'Snakeman', 'Supertype', 'ST', 'Luffy', 'Rufy', 'STR'],
        class: Class.FTR,
        classIcon: '',
        class2: Class.FSP,
        class2Icon: '',
        type: Type.STR,
        style: Style.ATK,
        styleIcon: '',
        rumbleSpecial: 'Level 10 (32 CT): Targets STR allies for tier 5 ATK boost (20 s.), targets 2 enemies for damage by 1.3x own ATK. When 30 or less seconds are left, targets mid-range enemies for damage by 2x own ATK',
        rumbleSkill: 'Level 5: Targets STR allies for tier 5 ATK boost and ter 1 SPD boost',
        rumblePattern: 'Normal, Normal, Strong, Full power',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Bind (50% chance)',
        tags: [DBFEnemy.DMG, BuffCrew.ATK, BuffCrew.SPD]
    },
    {
        id: 2964,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Blackbeard',
        name2: `Emperor`,
        altnames: ['V2', 'Legend', 'Blackbeard', 'BB', 'Super Type', 'ST', 'INT'],
        class: Class.DRV,
        classIcon: '',
        class2: Class.CER,
        class2Icon: '',
        type: Type.INT,
        style: Style.DEF,
        styleIcon: '',
        rumbleSpecial: 'Targets mid-range enemies for damage by 2x own ATK. Targets self for tier 10 ATK boost and tier 3 CT loading speed boost (25 s.)',
        rumbleSkill: 'Targets INT allies for HP boost (5 tiers), when HP is below 60% targets self for tier 5 CT loading speed boost',
        rumblePattern: 'Normal, Normal, Strong, Full power',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Seldom heals own HP by 150 when below 50%',
        tags: [DBFEnemy.DMG, BuffCrew.ATK, BuffCrew.CTS, BuffCrew.HP, BuffCrew.CTS]
    },
    {
        id: 2962,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Charlotte Katakuri',
        name2: 'Haki that Conquers the Future',
        altnames: ['V3', 'Katakuri', 'Super Type', 'ST', 'Legend'],
        class: Class.DRV,
        classIcon: '',
        class2: Class.FTR,
        class2Icon: '',
        type: Type.INT,
        style: Style.OBS,
        styleIcon: '',
        rumbleSpecial:  'Level 10 (28 CT): Targets all enemies for 2200 fixed damage, targets Free Spirit/Cerebral/Powerhouse enemies for tier 5 SPD down and CT loading speed reduction (20 s.)',
        rumbleSkill: 'Level 5: Targets INT allies for tier 5 SPD boost, targets PSY enemies for tier 4 DEF down and tier 5 CT loading speed down',
        rumblePattern: 'Normal, tier 2 Heal self, Strong, Normal',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Paralysis (50% chance)',
        tags: [DBFEnemy.DMG_FIXED, DBFEnemy.SPD, DBFEnemy.CTS, BuffCrew.SPD, DBFEnemy.DEF]
    },
    {
        id: 2980,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Eustass Kidd',
        name2: 'Magnetic Captain Challenging the Dragon',
        altnames: ['Kidd', 'Legend', 'Super Type', 'ST'],
        class: Class.DRV,
        classIcon: '',
        class2: Class.STK,
        class2Icon: '',
        type: Type.DEX,
        style: Style.DEF,
        styleIcon: '',
        rumbleSpecial:  'Level 10 (CT 28): Targets crew for tier 3 DEF boost (25 s.), targets enemies wide-range on the side for damage 2x own ATK',
        rumbleSkill: 'Targets DEX allies for tier 2 DEF boost and tier 5 HP boost',
        rumblePattern: 'Strong, Strong, tier 2 Heal self',
        rumbleTarget: 'Enemies with high ATK stat',
        rumbleResistances: 'DoT (50% chance)',
        tags: [BuffCrew.HP, BuffCrew.DEF, DBFEnemy.DMG]
    },
    {
        id: 3008,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Sugar',
        name2: 'Bulging Eyes of the Lord of the Toys',
        altnames: ['Legend', 'Sugar', 'Super Type', 'ST'],
        class: Class.DRV,
        classIcon: '',
        class2: Class.CER,
        class2Icon: '',
        type: Type.QCK,
        style: Style.OBS,
        styleIcon: '',
        rumbleSpecial:  'Level 10 (35 CT): Targets all enemies for tier 3 DEF down (18 s.), targets 2 STR enemies for tier 9 ATK down and SPD down (24 s.)',
        rumbleSkill: 'Level 5: First 20 seconds from start of the battle: tier 8 CT loading speed reduction for 3 STR enemies, targets QCK allies for tier 5 CT loading speed buff',
        rumblePattern: 'Normal, tier 1 Heal self, Normal, tier 2 Heal self',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Seldom recovers heals own HP by 250',
        tags: [DBFEnemy.DEF, DBFEnemy.SPD, DBFEnemy.CTS, BuffCrew.ATK]
    },
    {
        id: 3065,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Luffy&Sanji',
        name2: 'Faithful Friends at the Battlefront',
        altnames: ['Sanuffy', 'Dual', 'LuffySanji', 'legend'],
        class: Class.DUAL,
        classIcon: '',
        class2: Class.NONE,
        class2Icon: '',
        type: Type.DUAL,
        style: Style.ATK,
        styleIcon: '',
        rumbleSpecial:  'Level 10 (32 CT): Targets 2 enemies for damage by 3.5x own ATK. Targets crew for tier 5 ATK boost and tier 7 SPD boost (20 s.)',
        rumbleSkill: 'Level 5: Targets crew for tier 6 ATK boost and tier 3 SPD boost',
        rumblePattern: 'Normal, Normal, Strong, Full power',
        rumbleTarget: 'Enemy with highest HP left',
        rumbleResistances: 'Silence',
        tags: [DBFEnemy.DMG, BuffCrew.ATK, BuffCrew.SPD]
    },
    {
        id: 2850,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Rebecca&Viola',
        name2: 'Princesses of the Dressrosa Kingdom',
        altnames: ['ViolaBecca', 'TM', 'Dual'],
        class: Class.DUAL,
        classIcon: '',
        class2: Class.NONE,
        class2Icon: '',
        type: Type.DUAL,
        style: Style.HLR,
        styleIcon: '',
        rumbleSpecial:  'Level 10 (26 CT): Heals HP of allies wide range by 2.35x own RCV. First 50 seconds of battle, targets allies wide range for tier 5 ATK boost (24 s.)',
        rumbleSkill: 'Level 5: First 30 seconds of battle, targets crew for tier 6 CT loading speed boost',
        rumblePattern: 'Normal, tier 1 Heal surrounding allies (mid-range), Normal, tier 2 Heal surrounding allies (short range)',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Silence (30% chance)',
        tags: [HealCrew.HEAL, BuffCrew.ATK, BuffCrew.CTS]
    },
    {
        id: 1413,
        isExpanded: false,
        icon: '',
        artwork: '',
        unitName: 'Whitebeard',
        name2: 'Emperor',
        altnames: ['6+', 'legend', 'WB', 'V1'],
        class: Class.STK,
        classIcon: '',
        class2: Class.PWH,
        class2Icon: '',
        type: Type.STR,
        style: Style.ATK,
        styleIcon: '',
        rumbleSpecial:  'Level 10 (23 CT): Targets all enemies for 48% HP Cut',
        rumbleSkill: 'Level 5: When unit has 30% or less HP remaining, targets crew for tier 8 ATK boost and targets self for tier 8 DEF boost',
        rumblePattern: 'Normal, Strong, Full power',
        rumbleTarget: 'Closest enemy',
        rumbleResistances: 'Damage over Time (70% chance)',
        tags: [DBFEnemy.CUT, BuffCrew.ATK, BuffCrew.DEF]
    },
]